event/urls.py
from django.urls import path, include

from event import views

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')), # this is build in
    path('register/', views.register, name='register'), # custom
    path('login/', views.login, name='login'),
    path('', views.home, name='home'),
    path('events/create/', views.create_event, name='create_event'),
    path('events/upcoming/', views.upcoming_events, name='upcoming_events'),
    path('event/register/<int:event_id>/', views.register_event, name='register_event'),
    path('event/register/participate_events/', views.participate_events, name='participate_events'),
    path('event/register/registered_events/', views.user_registered_events, name='registered_events'),
    path('event/unregister/<int:event_id>/', views.unregister_event, name='unregister_event'),
    path('logout/', views.logout_view, name='logout'),


]

event_registration_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('event.urls')),
    path('api/',include('api_event.urls')),

]

event/models.py
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=100)
    slots_available = models.IntegerField()


    def __str__(self):
        return self.title




class Registration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    registration_time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"registration for {self.event.title} by {self.user.username}"

templates/create_event.html
{% extends 'partials/base.html' %}

{% block content %}
    <div class="container mt-5">
    <h2>Create Event</h2>
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_title" class="form-label"><i class="fas fa-heading"></i> Title:</label>
        <input type="text" class="form-control" id="id_title" name="title">
      </div>
      <div class="mb-3">
        <label for="id_description" class="form-label"><i class="fas fa-file-alt"></i> Description:</label>
        <textarea class="form-control" id="id_description" name="description" rows="3"></textarea>
      </div>
      <div class="row g-3">
        <div class="col-md-6">
          <label for="id_date" class="form-label"><i class="far fa-calendar-alt"></i> Date:</label>
          <input type="date" class="form-control" id="id_date" name="date">
        </div>
        <div class="col-md-6">
          <label for="id_time" class="form-label"><i class="far fa-clock"></i> Time:</label>
          <input type="time" class="form-control" id="id_time" name="time">
        </div>
      </div>
      <div class="mb-3">
        <label for="id_location" class="form-label"><i class="fas fa-map-marker-alt"></i> Location:</label>
        <input type="text" class="form-control" id="id_location" name="location">
      </div>
      <div class="mb-3">
        <label for="id_slots_available" class="form-label"><i class="fas fa-user-plus"></i> Slots Available:</label>
        <input type="number" class="form-control" id="id_slots_available" name="slots_available" min="1">
      </div>
      <button type="submit" class="btn btn-primary"><i class="fas fa-calendar-plus"></i> Create Event</button>
    </form>
  </div>

{% endblock content %}

templates/home.html
{% extends 'partials/base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1> All event</h1>
        <form action="{% url 'home' %}" method="GET">
            <input type="text" name="query" placeholder="Search events...">
            <button type="submit">Search</button>
        </form>

        <div class="row">
            {% for event in all_events %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.title }}</h5>
                        <p class="card-text">
                            <i class="far fa-calendar-alt"></i> Date: {{ event.date }}<br>
                            <i class="far fa-clock"></i> Time: {{ event.time }}<br>
                            <i class="fas fa-map-marker-alt"></i> Location: {{ event.location }}<br>
                            <i class="far fa-file-alt"></i> Description: {{ event.description }}<br>
                            <i class="fa fa-check"></i> Slot available: {{ event.slots_available }}<br>
                        </p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
                <p>No  events at the moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="Password"><br>
        <button type="submit">Login</button>
    </form>

</body>
</html>

templates/participate_events.html
{% extends 'partials/base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1>Participate events for {{ username }}</h1>


        <div class="row">
            {% for participate in participate_events %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ participate.event.title }}</h5>
                        <p class="card-text">
                            <i class="far fa-calendar-alt"></i> Date: {{ participate.event.date }}<br>
                            <i class="far fa-clock"></i> Time: {{ participate.event.time }}<br>
                            <i class="fas fa-map-marker-alt"></i> Location: {{ participate.event.location }}<br>
                            <i class="far fa-file-alt"></i> Description: {{ participate.event.description }}<br>


                        </p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
                <p>No participated events at the moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User registration</title>
</head>
<body>
<h2>User Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

</body>
</html>

templates/registered_events.html
{% extends 'partials/base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1>Registered events for {{ username }}</h1>


        <div class="row">
            {% for registration in registered_events %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ registration.event.title }}</h5>
                        <p class="card-text">
                            <i class="far fa-calendar-alt"></i> Date: {{ registration.event.date }}<br>
                            <i class="far fa-clock"></i> Time: {{ registration.event.time }}<br>
                            <i class="fas fa-map-marker-alt"></i> Location: {{ registration.event.location }}<br>
                            <i class="far fa-file-alt"></i> Description: {{ registration.event.description }}<br>
                            <i class="fa fa-check"></i> Slot available: {{ registration.event.slots_available }}<br>
                         <a href="{% url 'unregister_event' registration.event.id %}" class="btn btn-primary">
                                <i class="fa fa-remove"></i> UnRegister
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
                <p>No register events at the moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/upcoming_events.html
{% extends 'partials/base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1>Upcoming Events</h1>
        <p>Current Date and Time: {{ current_datetime }}</p>

        <div class="row">
            {% for event in upcoming_events %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.title }}</h5>
                        <p class="card-text">
                            <i class="far fa-calendar-alt"></i> Date: {{ event.date }}<br>
                            <i class="far fa-clock"></i> Time: {{ event.time }}<br>
                            <i class="fas fa-map-marker-alt"></i> Location: {{ event.location }}<br>
                            <i class="far fa-file-alt"></i> Description: {{ event.description }}<br>
                            {% if event.slots_available > 0 %}
                            <i class="fa fa-check"></i> Slot available: {{ event.slots_available }}

                            {% endif %}

                        </p>
                        {% if event.slots_available > 0 %}
                            <a href="{% url 'register_event' event.id %}" class="btn btn-primary">
                                <i class="fas fa-check-circle"></i> Register
                            </a>

                            {% else %}
                            <p class="text-danger text-capitalize">No slots available</p>
                        {% endif %}

                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
                <p>No ongoing events at the moment.</p>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}